/***
 *      _____ _   _  _____    _____ ____  _   _ _   _ ______ _______      __      __
 *     |_   _| \ | |/ ____|  / ____/ __ \| \ | | \ | |  ____|__   __|     \ \    / /
 *       | | |  \| | |      | |   | |  | |  \| |  \| | |__     | |         \ \  / / 
 *       | | | . ` | |      | |   | |  | | . ` | . ` |  __|    | |          \ \/ /  
 *      _| |_| |\  | |____  | |___| |__| | |\  | |\  | |____   | |     _     \  /   
 *     |_____|_| \_|\_____|  \_____\____/|_| \_|_| \_|______|  |_|    (_)     \/    
 *
 *                                                                  
 *  Desription: Connect Interactive ScriptFile
 *  
*/

#if !defined __ADAPTER_VIEW_EXPORT_INC

    forward useGameModeInit();
    forward usePlayerConnect(playerid);

    #define __ADAPTER_VIEW_EXPORT_INC
#endif
