/***
 *      _____ _   _  _____    _____ ____  _   _ _   _ ______ _______ 
 *     |_   _| \ | |/ ____|  / ____/ __ \| \ | | \ | |  ____|__   __|
 *       | | |  \| | |      | |   | |  | |  \| |  \| | |__     | |   
 *       | | | . ` | |      | |   | |  | | . ` | . ` |  __|    | |   
 *      _| |_| |\  | |____  | |___| |__| | |\  | |\  | |____   | |   
 *     |_____|_| \_|\_____|  \_____\____/|_| \_|_| \_|______|  |_|   
 *                                                                   
 *                                                                   
 *  Desription: connect all file to Appication.pwn for start point for compile on MVC Architecture.
 *  
*/

#if !defined __ADAPTER_INC
    #include <a_samp>
    #include <strlib>

    // DIR FOR VIEW
    #include <views/view>

    // DIR FOR MODULES
    #include <modules/module>

    // DIR FOR CONTROLLERS
    #include <controllers/controller>

    #define __ADAPTER_INC
#endif
